# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.federal_district_findings_list import FederalDistrictFindingsList

class TestFederalDistrictFindingsList(unittest.TestCase):
    """FederalDistrictFindingsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalDistrictFindingsList:
        """Test FederalDistrictFindingsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalDistrictFindingsList`
        """
        model = FederalDistrictFindingsList()
        if include_optional:
            return FederalDistrictFindingsList(
                court = lawmachine.models.court.Court(
                    name = '', 
                    type = 'FederalDistrict', ),
                findings_by_practice_area = {
                    'key' : [
                        ''
                        ]
                    },
                patent_invalidity_reasons = [
                    ''
                    ]
            )
        else:
            return FederalDistrictFindingsList(
                findings_by_practice_area = {
                    'key' : [
                        ''
                        ]
                    },
                patent_invalidity_reasons = [
                    ''
                    ],
        )
        """

    def testFederalDistrictFindingsList(self):
        """Test FederalDistrictFindingsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
