# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """SearchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SearchApi()

    def tearDown(self) -> None:
        pass

    def test_seach_law_firms_search_law_firms_get(self) -> None:
        """Test case for seach_law_firms_search_law_firms_get

        Seach Law Firms
        """
        pass

    def test_search_attorneys_search_attorneys_get(self) -> None:
        """Test case for search_attorneys_search_attorneys_get

        Search Attorneys
        """
        pass

    def test_search_judges_search_judges_get(self) -> None:
        """Test case for search_judges_search_judges_get

        Search Judges
        """
        pass

    def test_search_parties_search_parties_get(self) -> None:
        """Test case for search_parties_search_parties_get

        Search Parties
        """
        pass


if __name__ == '__main__':
    unittest.main()
