# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.ptab_decision_ground import PTABDecisionGround

class TestPTABDecisionGround(unittest.TestCase):
    """PTABDecisionGround unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PTABDecisionGround:
        """Test PTABDecisionGround
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PTABDecisionGround`
        """
        model = PTABDecisionGround()
        if include_optional:
            return PTABDecisionGround(
                decision = '',
                statute = '',
                claims = [
                    56
                    ],
                prior_art = [
                    lawmachine.models.prior_art.PriorArt(
                        prior_art_type = '', 
                        prior_art_references = [
                            ''
                            ], )
                    ]
            )
        else:
            return PTABDecisionGround(
                decision = '',
                statute = '',
                claims = [
                    56
                    ],
                prior_art = [
                    lawmachine.models.prior_art.PriorArt(
                        prior_art_type = '', 
                        prior_art_references = [
                            ''
                            ], )
                    ],
        )
        """

    def testPTABDecisionGround(self):
        """Test PTABDecisionGround"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
