# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.appeals_case import AppealsCase

class TestAppealsCase(unittest.TestCase):
    """AppealsCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealsCase:
        """Test AppealsCase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealsCase`
        """
        model = AppealsCase()
        if include_optional:
            return AppealsCase(
                appeals_case_id = 56,
                appeals_case_url = '',
                resolution = lawmachine.models.case_resolution.CaseResolution(
                    summary = '', 
                    specific = '', ),
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                terminated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return AppealsCase(
                appeals_case_id = 56,
                appeals_case_url = '',
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testAppealsCase(self):
        """Test AppealsCase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
