# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.originating_district_court_case import OriginatingDistrictCourtCase

class TestOriginatingDistrictCourtCase(unittest.TestCase):
    """OriginatingDistrictCourtCase unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OriginatingDistrictCourtCase:
        """Test OriginatingDistrictCourtCase
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OriginatingDistrictCourtCase`
        """
        model = OriginatingDistrictCourtCase()
        if include_optional:
            return OriginatingDistrictCourtCase(
                district_case_id = 56,
                district_case_url = '',
                judges = [
                    null
                    ],
                case_types = [
                    ''
                    ]
            )
        else:
            return OriginatingDistrictCourtCase(
                district_case_id = 56,
                district_case_url = '',
                judges = [
                    null
                    ],
                case_types = [
                    ''
                    ],
        )
        """

    def testOriginatingDistrictCourtCase(self):
        """Test OriginatingDistrictCourtCase"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
