# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.case_types_filter import CaseTypesFilter

class TestCaseTypesFilter(unittest.TestCase):
    """CaseTypesFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseTypesFilter:
        """Test CaseTypesFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseTypesFilter`
        """
        model = CaseTypesFilter()
        if include_optional:
            return CaseTypesFilter(
                include = [
                    ''
                    ],
                exclude = [
                    ''
                    ]
            )
        else:
            return CaseTypesFilter(
        )
        """

    def testCaseTypesFilter(self):
        """Test CaseTypesFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
