# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.federal_appeals_cases_api import FederalAppealsCasesApi


class TestFederalAppealsCasesApi(unittest.TestCase):
    """FederalAppealsCasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FederalAppealsCasesApi()

    def tearDown(self) -> None:
        pass

    def test_get_appeals_case_appeals_cases_appeals_case_id_get(self) -> None:
        """Test case for get_appeals_case_appeals_cases_appeals_case_id_get

        Get Appeals Case
        """
        pass

    def test_list_appealability_rulings_list_appealability_rulings_get(self) -> None:
        """Test case for list_appealability_rulings_list_appealability_rulings_get

        List Appealability Rulings
        """
        pass

    def test_list_appellate_decisions_list_appellate_decisions_federal_district_get(self) -> None:
        """Test case for list_appellate_decisions_list_appellate_decisions_federal_district_get

        List Appellate Decisions
        """
        pass

    def test_list_originating_venues_list_originating_venues_federal_appeals_get(self) -> None:
        """Test case for list_originating_venues_list_originating_venues_federal_appeals_get

        List Originating Venues
        """
        pass

    def test_list_supreme_court_decisions_list_supreme_court_decisions_federal_appeals_get(self) -> None:
        """Test case for list_supreme_court_decisions_list_supreme_court_decisions_federal_appeals_get

        List Supreme Court Decisions
        """
        pass

    def test_query_appeals_cases_query_appeals_cases_post(self) -> None:
        """Test case for query_appeals_cases_query_appeals_cases_post

        Query Appeals Cases
        """
        pass


if __name__ == '__main__':
    unittest.main()
