# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.state_cases_api import StateCasesApi


class TestStateCasesApi(unittest.TestCase):
    """StateCasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StateCasesApi()

    def tearDown(self) -> None:
        pass

    def test_get_state_case_state_cases_state_case_id_get(self) -> None:
        """Test case for get_state_case_state_cases_state_case_id_get

        Get State Case
        """
        pass

    def test_query_state_cases_query_state_cases_post(self) -> None:
        """Test case for query_state_cases_query_state_cases_post

        Query State Cases
        """
        pass


if __name__ == '__main__':
    unittest.main()
