# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.ptab_petition_stage_ground import PTABPetitionStageGround

class TestPTABPetitionStageGround(unittest.TestCase):
    """PTABPetitionStageGround unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PTABPetitionStageGround:
        """Test PTABPetitionStageGround
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PTABPetitionStageGround`
        """
        model = PTABPetitionStageGround()
        if include_optional:
            return PTABPetitionStageGround(
                statutes = [
                    ''
                    ],
                prior_art = [
                    lawmachine.models.prior_art.PriorArt(
                        prior_art_type = '', 
                        prior_art_references = [
                            ''
                            ], )
                    ]
            )
        else:
            return PTABPetitionStageGround(
                statutes = [
                    ''
                    ],
                prior_art = [
                    lawmachine.models.prior_art.PriorArt(
                        prior_art_type = '', 
                        prior_art_references = [
                            ''
                            ], )
                    ],
        )
        """

    def testPTABPetitionStageGround(self):
        """Test PTABPetitionStageGround"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
