# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.state_case_query import StateCaseQuery

class TestStateCaseQuery(unittest.TestCase):
    """StateCaseQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateCaseQuery:
        """Test StateCaseQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateCaseQuery`
        """
        model = StateCaseQuery()
        if include_optional:
            return StateCaseQuery(
                courts = lawmachine.models.state_court_filter.StateCourtFilter(
                    state = '', 
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                case_status = 'Open',
                case_types = lawmachine.models.case_types_filter.CaseTypesFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                case_tags = lawmachine.models.case_tags_filter.CaseTagsFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                dates = lawmachine.models.case_dates_filter.CaseDatesFilter(
                    filed = lawmachine.models.timing_filter.TimingFilter(
                        on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    terminated = lawmachine.models.timing_filter.TimingFilter(
                        on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    trial = , 
                    last_docket = , ),
                judges = lawmachine.models.judge_filter.JudgeFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], ),
                events = lawmachine.models.event_filter.EventFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                law_firms = lawmachine.models.law_firm_filter.LawFirmFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                attorneys = lawmachine.models.attorney_filter.AttorneyFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                parties = lawmachine.models.party_filter.PartyFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                resolutions = lawmachine.models.resolutions_filter.ResolutionsFilter(
                    include = [
                        lawmachine.models.individual_resolutions_filter.IndividualResolutionsFilter(
                            summary = '', 
                            specific = '', )
                        ], 
                    exclude = [
                        lawmachine.models.individual_resolutions_filter.IndividualResolutionsFilter(
                            summary = '', 
                            specific = '', )
                        ], ),
                damages = [
                    lawmachine.models.individual_state_damages_filter.IndividualStateDamagesFilter(
                        name = lawmachine.models.name_filter.NameFilter(
                            include = [
                                ''
                                ], 
                            exclude = [
                                ''
                                ], ), 
                        date = lawmachine.models.timing_filter.TimingFilter(
                            on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                        awarded_to_parties = [
                            56
                            ], 
                        awarded_against_parties = [
                            56
                            ], 
                        minimum_amount = null, )
                    ],
                rulings = [
                    lawmachine.models.individual_rulings_filter.IndividualRulingsFilter(
                        judgment_event = lawmachine.models.judgment_event_filter.JudgmentEventFilter(
                            include = [
                                ''
                                ], 
                            exclude = [
                                ''
                                ], ), 
                        awarded_to_parties = [
                            56
                            ], 
                        awarded_against_parties = [
                            56
                            ], 
                        date = lawmachine.models.timing_filter.TimingFilter(
                            on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), )
                    ],
                ordering = 'ByFirstFiled',
                page = 56,
                page_size = 56
            )
        else:
            return StateCaseQuery(
                courts = lawmachine.models.state_court_filter.StateCourtFilter(
                    state = '', 
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
        )
        """

    def testStateCaseQuery(self):
        """Test StateCaseQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
