# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.attorneys_api import AttorneysApi


class TestAttorneysApi(unittest.TestCase):
    """AttorneysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AttorneysApi()

    def tearDown(self) -> None:
        pass

    def test_get_attorney_attorneys_attorney_id_get(self) -> None:
        """Test case for get_attorney_attorneys_attorney_id_get

        Get Attorney
        """
        pass

    def test_get_attorneys_attorneys_get(self) -> None:
        """Test case for get_attorneys_attorneys_get

        Get Attorneys
        """
        pass

    def test_search_attorneys_search_attorneys_get(self) -> None:
        """Test case for search_attorneys_search_attorneys_get

        Search Attorneys
        """
        pass


if __name__ == '__main__':
    unittest.main()
