# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.district_case_findings_by_status import DistrictCaseFindingsByStatus

class TestDistrictCaseFindingsByStatus(unittest.TestCase):
    """DistrictCaseFindingsByStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistrictCaseFindingsByStatus:
        """Test DistrictCaseFindingsByStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistrictCaseFindingsByStatus`
        """
        model = DistrictCaseFindingsByStatus()
        if include_optional:
            return DistrictCaseFindingsByStatus(
                active = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                voided = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                reversed = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ]
            )
        else:
            return DistrictCaseFindingsByStatus(
                active = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                voided = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                reversed = [
                    lawmachine.models.district_case_finding.DistrictCaseFinding(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        in_favor_of_party_ids = [
                            56
                            ], 
                        patent_invalidity_reasons = [
                            ''
                            ], 
                        against_party_ids = [
                            56
                            ], 
                        docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        specific_reasons = [
                            ''
                            ], 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
        )
        """

    def testDistrictCaseFindingsByStatus(self):
        """Test DistrictCaseFindingsByStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
