# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.inventors import Inventors

class TestInventors(unittest.TestCase):
    """Inventors unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Inventors:
        """Test Inventors
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Inventors`
        """
        model = Inventors()
        if include_optional:
            return Inventors(
                inventors = [
                    ''
                    ],
                original_assignee = [
                    null
                    ],
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                issue_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return Inventors(
                inventors = [
                    ''
                    ],
                original_assignee = [
                    null
                    ],
                filing_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                issue_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testInventors(self):
        """Test Inventors"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
