# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.docket import Docket

class TestDocket(unittest.TestCase):
    """Docket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Docket:
        """Test Docket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Docket`
        """
        model = Docket()
        if include_optional:
            return Docket(
                entries = [
                    lawmachine.models.docket_entry.DocketEntry(
                        filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        tags = [
                            ''
                            ], 
                        text = '', 
                        number = 56, 
                        docket_entry_id = 56, )
                    ],
                retrieved = 'all',
                count = 56
            )
        else:
            return Docket(
                entries = [
                    lawmachine.models.docket_entry.DocketEntry(
                        filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        tags = [
                            ''
                            ], 
                        text = '', 
                        number = 56, 
                        docket_entry_id = 56, )
                    ],
                retrieved = 'all',
                count = 56,
        )
        """

    def testDocket(self):
        """Test Docket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
