# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.district_case_remedy import DistrictCaseRemedy

class TestDistrictCaseRemedy(unittest.TestCase):
    """DistrictCaseRemedy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistrictCaseRemedy:
        """Test DistrictCaseRemedy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistrictCaseRemedy`
        """
        model = DistrictCaseRemedy()
        if include_optional:
            return DistrictCaseRemedy(
                name = '',
                type = '',
                judgment_source = '',
                awarded_to_party_ids = [
                    56
                    ],
                against_party_ids = [
                    56
                    ],
                docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return DistrictCaseRemedy(
                name = '',
                type = '',
                judgment_source = '',
                awarded_to_party_ids = [
                    56
                    ],
                against_party_ids = [
                    56
                    ],
                docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testDistrictCaseRemedy(self):
        """Test DistrictCaseRemedy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
