# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.alert_item import AlertItem

class TestAlertItem(unittest.TestCase):
    """AlertItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AlertItem:
        """Test AlertItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AlertItem`
        """
        model = AlertItem()
        if include_optional:
            return AlertItem(
                url = '',
                item_id = None,
                district_case_id = 56,
                appeals_case_id = 56,
                state_case_id = 56,
                bankruptcy_case_id = 56,
                itc_investigation_number = '',
                ptab_trial_id = 56,
                district_case_url = '',
                appeals_case_url = '',
                state_case_url = '',
                bankruptcy_case_url = '',
                itc_investigation_url = '',
                ptab_trial_url = ''
            )
        else:
            return AlertItem(
        )
        """

    def testAlertItem(self):
        """Test AlertItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
