# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.originating_district_case_filter import OriginatingDistrictCaseFilter

class TestOriginatingDistrictCaseFilter(unittest.TestCase):
    """OriginatingDistrictCaseFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OriginatingDistrictCaseFilter:
        """Test OriginatingDistrictCaseFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OriginatingDistrictCaseFilter`
        """
        model = OriginatingDistrictCaseFilter()
        if include_optional:
            return OriginatingDistrictCaseFilter(
                courts = lawmachine.models.court_filter.CourtFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                case_types = lawmachine.models.originating_case_types_filter.OriginatingCaseTypesFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], )
            )
        else:
            return OriginatingDistrictCaseFilter(
        )
        """

    def testOriginatingDistrictCaseFilter(self):
        """Test OriginatingDistrictCaseFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
