# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.docket_entry import DocketEntry

class TestDocketEntry(unittest.TestCase):
    """DocketEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocketEntry:
        """Test DocketEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocketEntry`
        """
        model = DocketEntry()
        if include_optional:
            return DocketEntry(
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tags = [
                    ''
                    ],
                text = '',
                number = 56,
                docket_entry_id = 56
            )
        else:
            return DocketEntry(
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tags = [
                    ''
                    ],
                text = '',
                number = 56,
                docket_entry_id = 56,
        )
        """

    def testDocketEntry(self):
        """Test DocketEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
