# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.frequency import Frequency

class TestFrequency(unittest.TestCase):
    """Frequency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFrequency(self):
        """Test Frequency"""
        # inst = Frequency()

if __name__ == '__main__':
    unittest.main()
