# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.attorney_data import AttorneyData

class TestAttorneyData(unittest.TestCase):
    """AttorneyData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttorneyData:
        """Test AttorneyData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttorneyData`
        """
        model = AttorneyData()
        if include_optional:
            return AttorneyData(
                name = '',
                attorney_id = 56
            )
        else:
            return AttorneyData(
                name = '',
                attorney_id = 56,
        )
        """

    def testAttorneyData(self):
        """Test AttorneyData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
