# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.itc_investigations_api import ITCInvestigationsApi


class TestITCInvestigationsApi(unittest.TestCase):
    """ITCInvestigationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ITCInvestigationsApi()

    def tearDown(self) -> None:
        pass

    def test_get_itc_investigation_itc_investigations_itc_investigation_id_get(self) -> None:
        """Test case for get_itc_investigation_itc_investigations_itc_investigation_id_get

        Get Itc Investigation
        """
        pass


if __name__ == '__main__':
    unittest.main()
