# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.response_get_party_parties_party_id_get import ResponseGetPartyPartiesPartyIdGet

class TestResponseGetPartyPartiesPartyIdGet(unittest.TestCase):
    """ResponseGetPartyPartiesPartyIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetPartyPartiesPartyIdGet:
        """Test ResponseGetPartyPartiesPartyIdGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetPartyPartiesPartyIdGet`
        """
        model = ResponseGetPartyPartiesPartyIdGet()
        if include_optional:
            return ResponseGetPartyPartiesPartyIdGet(
                name = '',
                party_id = 56,
                input_id = 56,
                url = ''
            )
        else:
            return ResponseGetPartyPartiesPartyIdGet(
                name = '',
                party_id = 56,
                input_id = 56,
                url = '',
        )
        """

    def testResponseGetPartyPartiesPartyIdGet(self):
        """Test ResponseGetPartyPartiesPartyIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
