# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.state_case_dates import StateCaseDates

class TestStateCaseDates(unittest.TestCase):
    """StateCaseDates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateCaseDates:
        """Test StateCaseDates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateCaseDates`
        """
        model = StateCaseDates()
        if include_optional:
            return StateCaseDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                terminated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                trial = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return StateCaseDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                trial = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testStateCaseDates(self):
        """Test StateCaseDates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
