# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.federal_district_court import FederalDistrictCourt

class TestFederalDistrictCourt(unittest.TestCase):
    """FederalDistrictCourt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalDistrictCourt:
        """Test FederalDistrictCourt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalDistrictCourt`
        """
        model = FederalDistrictCourt()
        if include_optional:
            return FederalDistrictCourt(
                name = '',
                type = 'FederalDistrict',
                short_name = '',
                abbreviation = ''
            )
        else:
            return FederalDistrictCourt(
                name = '',
                type = 'FederalDistrict',
                short_name = '',
                abbreviation = '',
        )
        """

    def testFederalDistrictCourt(self):
        """Test FederalDistrictCourt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
