# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.itc_document_entity_data import ITCDocumentEntityData

class TestITCDocumentEntityData(unittest.TestCase):
    """ITCDocumentEntityData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ITCDocumentEntityData:
        """Test ITCDocumentEntityData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ITCDocumentEntityData`
        """
        model = ITCDocumentEntityData()
        if include_optional:
            return ITCDocumentEntityData(
                name = ''
            )
        else:
            return ITCDocumentEntityData(
                name = '',
        )
        """

    def testITCDocumentEntityData(self):
        """Test ITCDocumentEntityData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
