# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.federal_district_cases_api import FederalDistrictCasesApi


class TestFederalDistrictCasesApi(unittest.TestCase):
    """FederalDistrictCasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FederalDistrictCasesApi()

    def tearDown(self) -> None:
        pass

    def test_find_district_case_by_number_find_district_cases_get(self) -> None:
        """Test case for find_district_case_by_number_find_district_cases_get

        Find District Case By Number
        """
        pass

    def test_get_district_case_district_cases_district_case_id_get(self) -> None:
        """Test case for get_district_case_district_cases_district_case_id_get

        Get District Case
        """
        pass

    def test_query_district_cases_query_district_cases_post(self) -> None:
        """Test case for query_district_cases_query_district_cases_post

        Query District Cases
        """
        pass


if __name__ == '__main__':
    unittest.main()
