# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.parties_api import PartiesApi


class TestPartiesApi(unittest.TestCase):
    """PartiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PartiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_parties_parties_get(self) -> None:
        """Test case for get_parties_parties_get

        Get Parties
        """
        pass

    def test_get_party_parties_party_id_get(self) -> None:
        """Test case for get_party_parties_party_id_get

        Get Party
        """
        pass

    def test_search_parties_search_parties_get(self) -> None:
        """Test case for search_parties_search_parties_get

        Search Parties
        """
        pass


if __name__ == '__main__':
    unittest.main()
