# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.judgment_events_list import JudgmentEventsList

class TestJudgmentEventsList(unittest.TestCase):
    """JudgmentEventsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JudgmentEventsList:
        """Test JudgmentEventsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JudgmentEventsList`
        """
        model = JudgmentEventsList()
        if include_optional:
            return JudgmentEventsList(
                judgment_events = [
                    ''
                    ],
                court = lawmachine.models.court.Court(
                    name = '', 
                    type = 'FederalDistrict', )
            )
        else:
            return JudgmentEventsList(
                judgment_events = [
                    ''
                    ],
        )
        """

    def testJudgmentEventsList(self):
        """Test JudgmentEventsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
