# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.ptab_trials_api import PTABTrialsApi


class TestPTABTrialsApi(unittest.TestCase):
    """PTABTrialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PTABTrialsApi()

    def tearDown(self) -> None:
        pass

    def test_get_ptab_trial_ptab_trials_ptab_trial_id_get(self) -> None:
        """Test case for get_ptab_trial_ptab_trials_ptab_trial_id_get

        Get Ptab Trial
        """
        pass


if __name__ == '__main__':
    unittest.main()
