# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.docket_entries_included_in_output import DocketEntriesIncludedInOutput

class TestDocketEntriesIncludedInOutput(unittest.TestCase):
    """DocketEntriesIncludedInOutput unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDocketEntriesIncludedInOutput(self):
        """Test DocketEntriesIncludedInOutput"""
        # inst = DocketEntriesIncludedInOutput()

if __name__ == '__main__':
    unittest.main()
