# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.state_docket_entry import StateDocketEntry

class TestStateDocketEntry(unittest.TestCase):
    """StateDocketEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateDocketEntry:
        """Test StateDocketEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateDocketEntry`
        """
        model = StateDocketEntry()
        if include_optional:
            return StateDocketEntry(
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tags = [
                    ''
                    ],
                text = '',
                state_docket_entry_id = 56
            )
        else:
            return StateDocketEntry(
                filed_on = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                tags = [
                    ''
                    ],
                text = '',
                state_docket_entry_id = 56,
        )
        """

    def testStateDocketEntry(self):
        """Test StateDocketEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
