# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.district_case_query import DistrictCaseQuery

class TestDistrictCaseQuery(unittest.TestCase):
    """DistrictCaseQuery unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistrictCaseQuery:
        """Test DistrictCaseQuery
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistrictCaseQuery`
        """
        model = DistrictCaseQuery()
        if include_optional:
            return DistrictCaseQuery(
                case_status = 'Open',
                case_types = lawmachine.models.case_types_filter.CaseTypesFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                case_tags = lawmachine.models.case_tags_filter.CaseTagsFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                dates = lawmachine.models.case_dates_filter.CaseDatesFilter(
                    filed = lawmachine.models.timing_filter.TimingFilter(
                        on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    terminated = lawmachine.models.timing_filter.TimingFilter(
                        on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                    trial = , 
                    last_docket = , ),
                judges = lawmachine.models.judge_filter.JudgeFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], ),
                magistrates = lawmachine.models.magistrate_filter.MagistrateFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], ),
                events = lawmachine.models.event_filter.EventFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                law_firms = lawmachine.models.law_firm_filter.LawFirmFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                attorneys = lawmachine.models.attorney_filter.AttorneyFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                parties = lawmachine.models.party_filter.PartyFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], 
                    include_plaintiff = [
                        56
                        ], 
                    exclude_plaintiff = [
                        56
                        ], 
                    include_defendant = [
                        56
                        ], 
                    exclude_defendant = [
                        56
                        ], 
                    include_third_party = [
                        56
                        ], 
                    exclude_third_party = [
                        56
                        ], ),
                courts = lawmachine.models.court_filter.CourtFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                resolutions = lawmachine.models.resolutions_filter.ResolutionsFilter(
                    include = [
                        lawmachine.models.individual_resolutions_filter.IndividualResolutionsFilter(
                            summary = '', 
                            specific = '', )
                        ], 
                    exclude = [
                        lawmachine.models.individual_resolutions_filter.IndividualResolutionsFilter(
                            summary = '', 
                            specific = '', )
                        ], ),
                findings = [
                    lawmachine.models.individual_findings_filter.IndividualFindingsFilter(
                        judgment_source = lawmachine.models.judgment_source_filter.JudgmentSourceFilter(
                            include = [
                                ''
                                ], 
                            exclude = [
                                ''
                                ], ), 
                        name_type = lawmachine.models.name_type_filter.NameTypeFilter(), 
                        date = lawmachine.models.timing_filter.TimingFilter(
                            on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                        awarded_to_parties = [
                            56
                            ], 
                        awarded_against_parties = [
                            56
                            ], 
                        patent_invalidity_reasons = lawmachine.models.patent_invalidity_reasons_filter.PatentInvalidityReasonsFilter(), )
                    ],
                remedies = [
                    lawmachine.models.individual_remedies_filter.IndividualRemediesFilter(
                        judgment_source = lawmachine.models.judgment_source_filter.JudgmentSourceFilter(
                            include = [
                                ''
                                ], 
                            exclude = [
                                ''
                                ], ), 
                        name_type = lawmachine.models.name_type_filter.NameTypeFilter(), 
                        date = lawmachine.models.timing_filter.TimingFilter(
                            on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                        awarded_to_parties = [
                            56
                            ], 
                        awarded_against_parties = [
                            56
                            ], )
                    ],
                damages = [
                    lawmachine.models.individual_damages_filter.IndividualDamagesFilter(
                        judgment_source = lawmachine.models.judgment_source_filter.JudgmentSourceFilter(
                            include = [
                                ''
                                ], 
                            exclude = [
                                ''
                                ], ), 
                        name_type = lawmachine.models.name_type_filter.NameTypeFilter(), 
                        date = lawmachine.models.timing_filter.TimingFilter(
                            on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                            on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                        awarded_to_parties = [
                            56
                            ], 
                        awarded_against_parties = [
                            56
                            ], 
                        minimum_amount = null, )
                    ],
                patents = lawmachine.models.patent_filter.PatentFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                mdl = lawmachine.models.multidistrict_litigation_filter.MultidistrictLitigationFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], ),
                appellate_decisions = lawmachine.models.appellate_decision_filter.AppellateDecisionFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                ordering = 'ByFirstFiled',
                page = 56,
                page_size = 56
            )
        else:
            return DistrictCaseQuery(
        )
        """

    def testDistrictCaseQuery(self):
        """Test DistrictCaseQuery"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
