# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.itc_document_data import ITCDocumentData

class TestITCDocumentData(unittest.TestCase):
    """ITCDocumentData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ITCDocumentData:
        """Test ITCDocumentData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ITCDocumentData`
        """
        model = ITCDocumentData()
        if include_optional:
            return ITCDocumentData(
                usitc_document_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                title = '',
                type = '',
                filed_by = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                firm = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                on_behalf_of = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                investigation_number = ''
            )
        else:
            return ITCDocumentData(
                usitc_document_id = 56,
                var_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                title = '',
                type = '',
                filed_by = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                firm = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                on_behalf_of = [
                    lawmachine.models.itc_document_entity_data.ITCDocumentEntityData(
                        name = '', )
                    ],
                investigation_number = '',
        )
        """

    def testITCDocumentData(self):
        """Test ITCDocumentData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
