# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.appeals_case_dates import AppealsCaseDates

class TestAppealsCaseDates(unittest.TestCase):
    """AppealsCaseDates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealsCaseDates:
        """Test AppealsCaseDates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealsCaseDates`
        """
        model = AppealsCaseDates()
        if include_optional:
            return AppealsCaseDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                terminated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                last_docket = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return AppealsCaseDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                last_docket = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testAppealsCaseDates(self):
        """Test AppealsCaseDates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
