# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.case_resolutions_list import CaseResolutionsList

class TestCaseResolutionsList(unittest.TestCase):
    """CaseResolutionsList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CaseResolutionsList:
        """Test CaseResolutionsList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CaseResolutionsList`
        """
        model = CaseResolutionsList()
        if include_optional:
            return CaseResolutionsList(
                court = lawmachine.models.court.Court(
                    name = '', 
                    type = 'FederalDistrict', ),
                case_resolutions = [
                    lawmachine.models.case_resolution.CaseResolution(
                        summary = '', 
                        specific = '', )
                    ]
            )
        else:
            return CaseResolutionsList(
                court = lawmachine.models.court.Court(
                    name = '', 
                    type = 'FederalDistrict', ),
                case_resolutions = [
                    lawmachine.models.case_resolution.CaseResolution(
                        summary = '', 
                        specific = '', )
                    ],
        )
        """

    def testCaseResolutionsList(self):
        """Test CaseResolutionsList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
