# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.district_case_damages_by_status import DistrictCaseDamagesByStatus

class TestDistrictCaseDamagesByStatus(unittest.TestCase):
    """DistrictCaseDamagesByStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistrictCaseDamagesByStatus:
        """Test DistrictCaseDamagesByStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistrictCaseDamagesByStatus`
        """
        model = DistrictCaseDamagesByStatus()
        if include_optional:
            return DistrictCaseDamagesByStatus(
                active = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                voided = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                reversed = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ]
            )
        else:
            return DistrictCaseDamagesByStatus(
                active = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                voided = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
                reversed = [
                    lawmachine.models.district_case_damages.DistrictCaseDamages(
                        name = '', 
                        type = '', 
                        judgment_source = '', 
                        awarded_to_party_ids = [
                            56
                            ], 
                        awarded_against_party_ids = [
                            56
                            ], 
                        amount = null, 
                        awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        negated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        reinstated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
                    ],
        )
        """

    def testDistrictCaseDamagesByStatus(self):
        """Test DistrictCaseDamagesByStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
