# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.federal_judge_data import FederalJudgeData

class TestFederalJudgeData(unittest.TestCase):
    """FederalJudgeData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalJudgeData:
        """Test FederalJudgeData
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalJudgeData`
        """
        model = FederalJudgeData()
        if include_optional:
            return FederalJudgeData(
                name = '',
                federal_judge_id = 56,
                initials = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                case_count_by_court = [
                    lawmachine.models.case_count_by_court.CaseCountByCourt(
                        court = '', 
                        count = 56, )
                    ],
                nominating_president = ''
            )
        else:
            return FederalJudgeData(
                name = '',
                federal_judge_id = 56,
                initials = '',
                date_of_birth = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                case_count_by_court = [
                    lawmachine.models.case_count_by_court.CaseCountByCourt(
                        court = '', 
                        count = 56, )
                    ],
                nominating_president = '',
        )
        """

    def testFederalJudgeData(self):
        """Test FederalJudgeData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
