# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.find_api import FindApi


class TestFindApi(unittest.TestCase):
    """FindApi unit test stubs"""

    def setUp(self) -> None:
        self.api = FindApi()

    def tearDown(self) -> None:
        pass

    def test_find_district_case_by_number_find_district_cases_get(self) -> None:
        """Test case for find_district_case_by_number_find_district_cases_get

        Find District Case By Number
        """
        pass


if __name__ == '__main__':
    unittest.main()
