# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.models.appeals_law_firm_filter import AppealsLawFirmFilter

class TestAppealsLawFirmFilter(unittest.TestCase):
    """AppealsLawFirmFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealsLawFirmFilter:
        """Test AppealsLawFirmFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealsLawFirmFilter`
        """
        model = AppealsLawFirmFilter()
        if include_optional:
            return AppealsLawFirmFilter(
                include = [
                    56
                    ],
                exclude = [
                    56
                    ],
                include_appellant = [
                    56
                    ],
                exclude_appellant = [
                    56
                    ],
                include_appellee = [
                    56
                    ],
                exclude_appellee = [
                    56
                    ],
                include_respondent = [
                    56
                    ],
                exclude_respondent = [
                    56
                    ],
                include_third_party = [
                    56
                    ],
                exclude_third_party = [
                    56
                    ],
                include_petitioner_movant = [
                    56
                    ],
                exclude_petitioner_movant = [
                    56
                    ]
            )
        else:
            return AppealsLawFirmFilter(
        )
        """

    def testAppealsLawFirmFilter(self):
        """Test AppealsLawFirmFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
