# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from lawmachine.api.entities_api import EntitiesApi


class TestEntitiesApi(unittest.TestCase):
    """EntitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EntitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_attorney_attorneys_attorney_id_get(self) -> None:
        """Test case for get_attorney_attorneys_attorney_id_get

        Get Attorney
        """
        pass

    def test_get_attorneys_attorneys_get(self) -> None:
        """Test case for get_attorneys_attorneys_get

        Get Attorneys
        """
        pass

    def test_get_bankruptcy_judge_bankruptcy_judges_bankruptcy_judge_id_get(self) -> None:
        """Test case for get_bankruptcy_judge_bankruptcy_judges_bankruptcy_judge_id_get

        Get Bankruptcy Judge
        """
        pass

    def test_get_bankruptcy_judges_bankruptcy_judges_get(self) -> None:
        """Test case for get_bankruptcy_judges_bankruptcy_judges_get

        Get Bankruptcy Judges
        """
        pass

    def test_get_federal_judge_federal_judges_federal_judge_id_get(self) -> None:
        """Test case for get_federal_judge_federal_judges_federal_judge_id_get

        Get Federal Judge
        """
        pass

    def test_get_federal_judges_federal_judges_get(self) -> None:
        """Test case for get_federal_judges_federal_judges_get

        Get Federal Judges
        """
        pass

    def test_get_law_firm_law_firms_law_firm_id_get(self) -> None:
        """Test case for get_law_firm_law_firms_law_firm_id_get

        Get Law Firm
        """
        pass

    def test_get_law_firms_law_firms_get(self) -> None:
        """Test case for get_law_firms_law_firms_get

        Get Law Firms
        """
        pass

    def test_get_magistrate_magistrate_judges_magistrate_judge_id_get(self) -> None:
        """Test case for get_magistrate_magistrate_judges_magistrate_judge_id_get

        Get Magistrate
        """
        pass

    def test_get_magistrates_magistrate_judges_get(self) -> None:
        """Test case for get_magistrates_magistrate_judges_get

        Get Magistrates
        """
        pass

    def test_get_parties_parties_get(self) -> None:
        """Test case for get_parties_parties_get

        Get Parties
        """
        pass

    def test_get_party_parties_party_id_get(self) -> None:
        """Test case for get_party_parties_party_id_get

        Get Party
        """
        pass

    def test_get_state_judge_state_judges_state_judge_id_get(self) -> None:
        """Test case for get_state_judge_state_judges_state_judge_id_get

        Get State Judge
        """
        pass

    def test_get_state_judges_state_judges_get(self) -> None:
        """Test case for get_state_judges_state_judges_get

        Get State Judges
        """
        pass


if __name__ == '__main__':
    unittest.main()
