# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20251118
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from lexmachina.models.counts_per_role import CountsPerRole
from typing import Optional, Set
from typing_extensions import Self

class LawFirmCountByRole(BaseModel):
    """
    LawFirmCountByRole
    """ # noqa: E501
    law_firm_id: StrictInt = Field(alias="lawFirmId")
    law_firm_name: StrictStr = Field(alias="lawFirmName")
    roles_and_counts: List[CountsPerRole] = Field(alias="rolesAndCounts")
    __properties: ClassVar[List[str]] = ["lawFirmId", "lawFirmName", "rolesAndCounts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of LawFirmCountByRole from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in roles_and_counts (list)
        _items = []
        if self.roles_and_counts:
            for _item_roles_and_counts in self.roles_and_counts:
                if _item_roles_and_counts:
                    _items.append(_item_roles_and_counts.to_dict())
            _dict['rolesAndCounts'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of LawFirmCountByRole from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "lawFirmId": obj.get("lawFirmId"),
            "lawFirmName": obj.get("lawFirmName"),
            "rolesAndCounts": [CountsPerRole.from_dict(_item) for _item in obj["rolesAndCounts"]] if obj.get("rolesAndCounts") is not None else None
        })
        return _obj


