# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.individual_findings_filter import IndividualFindingsFilter

class TestIndividualFindingsFilter(unittest.TestCase):
    """IndividualFindingsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndividualFindingsFilter:
        """Test IndividualFindingsFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndividualFindingsFilter`
        """
        model = IndividualFindingsFilter()
        if include_optional:
            return IndividualFindingsFilter(
                judgment_source = openapi_client.models.judgment_source_filter.JudgmentSourceFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                name_type = openapi_client.models.name_type_filter.NameTypeFilter(
                    include = [
                        openapi_client.models.individual_name_type_filter.IndividualNameTypeFilter(
                            name = '', 
                            type = '', )
                        ], 
                    exclude = [
                        openapi_client.models.individual_name_type_filter.IndividualNameTypeFilter(
                            name = '', 
                            type = '', )
                        ], ),
                var_date = openapi_client.models.timing_filter.TimingFilter(
                    on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                awarded_to_parties = [
                    56
                    ],
                awarded_against_parties = [
                    56
                    ],
                patent_invalidity_reasons = openapi_client.models.patent_invalidity_reasons_filter.PatentInvalidityReasonsFilter(
                    include = [
                        ''
                        ], )
            )
        else:
            return IndividualFindingsFilter(
        )
        """

    def testIndividualFindingsFilter(self):
        """Test IndividualFindingsFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
