# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.law_firms_api import LawFirmsApi


class TestLawFirmsApi(unittest.TestCase):
    """LawFirmsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = LawFirmsApi()

    def tearDown(self) -> None:
        pass

    def test_get_law_firm_law_firms_law_firm_id_get(self) -> None:
        """Test case for get_law_firm_law_firms_law_firm_id_get

        Get Law Firm
        """
        pass

    def test_get_law_firms_law_firms_get(self) -> None:
        """Test case for get_law_firms_law_firms_get

        Get Law Firms
        """
        pass

    def test_seach_law_firms_search_law_firms_get(self) -> None:
        """Test case for seach_law_firms_search_law_firms_get

        Seach Law Firms
        """
        pass


if __name__ == '__main__':
    unittest.main()
