# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.alerts_api import AlertsApi


class TestAlertsApi(unittest.TestCase):
    """AlertsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AlertsApi()

    def tearDown(self) -> None:
        pass

    def test_get_alert_run_results_alerts_runs_alert_id_date_get(self) -> None:
        """Test case for get_alert_run_results_alerts_runs_alert_id_date_get

        Get Alert Run Results
        """
        pass

    def test_get_alert_runs_alerts_runs_alert_id_get(self) -> None:
        """Test case for get_alert_runs_alerts_runs_alert_id_get

        Get Alert Runs
        """
        pass

    def test_get_alerts_alerts_get(self) -> None:
        """Test case for get_alerts_alerts_get

        Get Alerts
        """
        pass


if __name__ == '__main__':
    unittest.main()
