# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_parties_parties_get200_response_inner import GetPartiesPartiesGet200ResponseInner

class TestGetPartiesPartiesGet200ResponseInner(unittest.TestCase):
    """GetPartiesPartiesGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetPartiesPartiesGet200ResponseInner:
        """Test GetPartiesPartiesGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetPartiesPartiesGet200ResponseInner`
        """
        model = GetPartiesPartiesGet200ResponseInner()
        if include_optional:
            return GetPartiesPartiesGet200ResponseInner(
                name = '',
                party_id = 56,
                input_id = 56,
                url = ''
            )
        else:
            return GetPartiesPartiesGet200ResponseInner(
                name = '',
                party_id = 56,
                input_id = 56,
                url = '',
        )
        """

    def testGetPartiesPartiesGet200ResponseInner(self):
        """Test GetPartiesPartiesGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
