# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.federal_district_damages_list import FederalDistrictDamagesList

class TestFederalDistrictDamagesList(unittest.TestCase):
    """FederalDistrictDamagesList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalDistrictDamagesList:
        """Test FederalDistrictDamagesList
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalDistrictDamagesList`
        """
        model = FederalDistrictDamagesList()
        if include_optional:
            return FederalDistrictDamagesList(
                court = openapi_client.models.court.Court(
                    name = '', 
                    type = 'FederalDistrict', ),
                damages_by_pratice_area = {
                    'key' : [
                        ''
                        ]
                    }
            )
        else:
            return FederalDistrictDamagesList(
                damages_by_pratice_area = {
                    'key' : [
                        ''
                        ]
                    },
        )
        """

    def testFederalDistrictDamagesList(self):
        """Test FederalDistrictDamagesList"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
