# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.expert_witness import ExpertWitness

class TestExpertWitness(unittest.TestCase):
    """ExpertWitness unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ExpertWitness:
        """Test ExpertWitness
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ExpertWitness`
        """
        model = ExpertWitness()
        if include_optional:
            return ExpertWitness(
                name = '',
                expert_witness_id = 56
            )
        else:
            return ExpertWitness(
                name = '',
                expert_witness_id = 56,
        )
        """

    def testExpertWitness(self):
        """Test ExpertWitness"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
