# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.unspecified_damages_amount import UnspecifiedDamagesAmount

class TestUnspecifiedDamagesAmount(unittest.TestCase):
    """UnspecifiedDamagesAmount unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUnspecifiedDamagesAmount(self):
        """Test UnspecifiedDamagesAmount"""
        # inst = UnspecifiedDamagesAmount()

if __name__ == '__main__':
    unittest.main()
