# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.originating_judge_filter import OriginatingJudgeFilter

class TestOriginatingJudgeFilter(unittest.TestCase):
    """OriginatingJudgeFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OriginatingJudgeFilter:
        """Test OriginatingJudgeFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OriginatingJudgeFilter`
        """
        model = OriginatingJudgeFilter()
        if include_optional:
            return OriginatingJudgeFilter(
                district_federal_judges = openapi_client.models.judge_filter.JudgeFilter(
                    include = [
                        56
                        ], 
                    exclude = [
                        56
                        ], )
            )
        else:
            return OriginatingJudgeFilter(
        )
        """

    def testOriginatingJudgeFilter(self):
        """Test OriginatingJudgeFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
