# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.appellate_decision_filter import AppellateDecisionFilter

class TestAppellateDecisionFilter(unittest.TestCase):
    """AppellateDecisionFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppellateDecisionFilter:
        """Test AppellateDecisionFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppellateDecisionFilter`
        """
        model = AppellateDecisionFilter()
        if include_optional:
            return AppellateDecisionFilter(
                include = [
                    ''
                    ],
                exclude = [
                    ''
                    ]
            )
        else:
            return AppellateDecisionFilter(
        )
        """

    def testAppellateDecisionFilter(self):
        """Test AppellateDecisionFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
