# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.ptab_trial_dates import PTABTrialDates

class TestPTABTrialDates(unittest.TestCase):
    """PTABTrialDates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PTABTrialDates:
        """Test PTABTrialDates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PTABTrialDates`
        """
        model = PTABTrialDates()
        if include_optional:
            return PTABTrialDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                terminated = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                institution_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                final_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return PTABTrialDates(
                filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                institution_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                final_decision = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testPTABTrialDates(self):
        """Test PTABTrialDates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
