# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.individual_rulings_filter import IndividualRulingsFilter

class TestIndividualRulingsFilter(unittest.TestCase):
    """IndividualRulingsFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IndividualRulingsFilter:
        """Test IndividualRulingsFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IndividualRulingsFilter`
        """
        model = IndividualRulingsFilter()
        if include_optional:
            return IndividualRulingsFilter(
                judgment_event = openapi_client.models.judgment_event_filter.JudgmentEventFilter(
                    include = [
                        ''
                        ], 
                    exclude = [
                        ''
                        ], ),
                awarded_to_parties = [
                    56
                    ],
                awarded_against_parties = [
                    56
                    ],
                var_date = openapi_client.models.timing_filter.TimingFilter(
                    on_or_after = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    on_or_before = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), )
            )
        else:
            return IndividualRulingsFilter(
        )
        """

    def testIndividualRulingsFilter(self):
        """Test IndividualRulingsFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
