# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.state_docket import StateDocket

class TestStateDocket(unittest.TestCase):
    """StateDocket unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StateDocket:
        """Test StateDocket
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StateDocket`
        """
        model = StateDocket()
        if include_optional:
            return StateDocket(
                entries = [
                    {
                        'key' : null
                        }
                    ],
                retrieved = 'all',
                count = 56
            )
        else:
            return StateDocket(
                entries = [
                    {
                        'key' : null
                        }
                    ],
                retrieved = 'all',
                count = 56,
        )
        """

    def testStateDocket(self):
        """Test StateDocket"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
