# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.dockets_api import DocketsApi


class TestDocketsApi(unittest.TestCase):
    """DocketsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocketsApi()

    def tearDown(self) -> None:
        pass

    def test_get_docket_entry_docket_entries_docket_entry_id_get(self) -> None:
        """Test case for get_docket_entry_docket_entries_docket_entry_id_get

        Get Docket Entry
        """
        pass

    def test_get_itc_document_entry_itc_document_entries_usitc_document_id_get(self) -> None:
        """Test case for get_itc_document_entry_itc_document_entries_usitc_document_id_get

        Get Itc Document Entry
        """
        pass


if __name__ == '__main__':
    unittest.main()
