# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.authorization_api import AuthorizationApi


class TestAuthorizationApi(unittest.TestCase):
    """AuthorizationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AuthorizationApi()

    def tearDown(self) -> None:
        pass

    def test_oauth2_token_oauth2_token_post(self) -> None:
        """Test case for oauth2_token_oauth2_token_post

        Oauth2 Token
        """
        pass


if __name__ == '__main__':
    unittest.main()
