# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.federal_judge import FederalJudge

class TestFederalJudge(unittest.TestCase):
    """FederalJudge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FederalJudge:
        """Test FederalJudge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FederalJudge`
        """
        model = FederalJudge()
        if include_optional:
            return FederalJudge(
                name = '',
                federal_judge_id = 56
            )
        else:
            return FederalJudge(
                name = '',
                federal_judge_id = 56,
        )
        """

    def testFederalJudge(self):
        """Test FederalJudge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
