# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.list_api import ListApi


class TestListApi(unittest.TestCase):
    """ListApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ListApi()

    def tearDown(self) -> None:
        pass

    def test_list_appealability_rulings_list_appealability_rulings_get(self) -> None:
        """Test case for list_appealability_rulings_list_appealability_rulings_get

        List Appealability Rulings
        """
        pass

    def test_list_appellate_decisions_list_appellate_decisions_federal_district_get(self) -> None:
        """Test case for list_appellate_decisions_list_appellate_decisions_federal_district_get

        List Appellate Decisions
        """
        pass

    def test_list_case_resolutions_list_case_resolutions_court_type_get(self) -> None:
        """Test case for list_case_resolutions_list_case_resolutions_court_type_get

        List Case Resolutions
        """
        pass

    def test_list_case_tags_list_case_tags_court_type_get(self) -> None:
        """Test case for list_case_tags_list_case_tags_court_type_get

        List Case Tags
        """
        pass

    def test_list_case_types_list_case_types_court_type_get(self) -> None:
        """Test case for list_case_types_list_case_types_court_type_get

        List Case Types
        """
        pass

    def test_list_courts_list_courts_court_type_get(self) -> None:
        """Test case for list_courts_list_courts_court_type_get

        List Courts
        """
        pass

    def test_list_events_list_events_court_type_get(self) -> None:
        """Test case for list_events_list_events_court_type_get

        List Events
        """
        pass

    def test_list_federal_district_damages_list_damages_federal_district_get(self) -> None:
        """Test case for list_federal_district_damages_list_damages_federal_district_get

        List Federal District Damages
        """
        pass

    def test_list_federal_district_findings_list_findings_federal_district_get(self) -> None:
        """Test case for list_federal_district_findings_list_findings_federal_district_get

        List Federal District Findings
        """
        pass

    def test_list_judgment_events_list_judgment_events_state_get(self) -> None:
        """Test case for list_judgment_events_list_judgment_events_state_get

        List Judgment Events
        """
        pass

    def test_list_judgment_sources_list_judgment_sources_federal_district_get(self) -> None:
        """Test case for list_judgment_sources_list_judgment_sources_federal_district_get

        List Judgment Sources
        """
        pass

    def test_list_originating_venues_list_originating_venues_federal_appeals_get(self) -> None:
        """Test case for list_originating_venues_list_originating_venues_federal_appeals_get

        List Originating Venues
        """
        pass

    def test_list_state_damages_list_damages_state_get(self) -> None:
        """Test case for list_state_damages_list_damages_state_get

        List State Damages
        """
        pass

    def test_list_supreme_court_decisions_list_supreme_court_decisions_federal_appeals_get(self) -> None:
        """Test case for list_supreme_court_decisions_list_supreme_court_decisions_federal_appeals_get

        List Supreme Court Decisions
        """
        pass


if __name__ == '__main__':
    unittest.main()
