# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.magistrate_judge import MagistrateJudge

class TestMagistrateJudge(unittest.TestCase):
    """MagistrateJudge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MagistrateJudge:
        """Test MagistrateJudge
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MagistrateJudge`
        """
        model = MagistrateJudge()
        if include_optional:
            return MagistrateJudge(
                name = '',
                magistrate_judge_id = 56
            )
        else:
            return MagistrateJudge(
                name = '',
                magistrate_judge_id = 56,
        )
        """

    def testMagistrateJudge(self):
        """Test MagistrateJudge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
