# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_law_firms_law_firms_get200_response_inner import GetLawFirmsLawFirmsGet200ResponseInner

class TestGetLawFirmsLawFirmsGet200ResponseInner(unittest.TestCase):
    """GetLawFirmsLawFirmsGet200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetLawFirmsLawFirmsGet200ResponseInner:
        """Test GetLawFirmsLawFirmsGet200ResponseInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetLawFirmsLawFirmsGet200ResponseInner`
        """
        model = GetLawFirmsLawFirmsGet200ResponseInner()
        if include_optional:
            return GetLawFirmsLawFirmsGet200ResponseInner(
                name = '',
                law_firm_id = 56,
                input_id = 56,
                url = ''
            )
        else:
            return GetLawFirmsLawFirmsGet200ResponseInner(
                name = '',
                law_firm_id = 56,
                input_id = 56,
                url = '',
        )
        """

    def testGetLawFirmsLawFirmsGet200ResponseInner(self):
        """Test GetLawFirmsLawFirmsGet200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
