# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.case_query_api import CaseQueryApi


class TestCaseQueryApi(unittest.TestCase):
    """CaseQueryApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CaseQueryApi()

    def tearDown(self) -> None:
        pass

    def test_query_appeals_cases_query_appeals_cases_post(self) -> None:
        """Test case for query_appeals_cases_query_appeals_cases_post

        Query Appeals Cases
        """
        pass

    def test_query_district_cases_query_district_cases_post(self) -> None:
        """Test case for query_district_cases_query_district_cases_post

        Query District Cases
        """
        pass

    def test_query_state_cases_query_state_cases_post(self) -> None:
        """Test case for query_state_cases_query_state_cases_post

        Query State Cases
        """
        pass


if __name__ == '__main__':
    unittest.main()
