# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.alert import Alert

class TestAlert(unittest.TestCase):
    """Alert unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Alert:
        """Test Alert
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Alert`
        """
        model = Alert()
        if include_optional:
            return Alert(
                alert_id = 56,
                type = '',
                custom_name = '',
                frequency = 'Daily',
                last_run = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                alert_url = '',
                law_url = ''
            )
        else:
            return Alert(
                alert_id = 56,
                type = '',
                custom_name = '',
                frequency = 'Daily',
                last_run = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                alert_url = '',
                law_url = '',
        )
        """

    def testAlert(self):
        """Test Alert"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
