# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.bankruptcy_cases_api import BankruptcyCasesApi


class TestBankruptcyCasesApi(unittest.TestCase):
    """BankruptcyCasesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BankruptcyCasesApi()

    def tearDown(self) -> None:
        pass

    def test_get_bankruptcy_case_bankruptcy_cases_bankruptcy_case_id_get(self) -> None:
        """Test case for get_bankruptcy_case_bankruptcy_cases_bankruptcy_case_id_get

        Get Bankruptcy Case
        """
        pass


if __name__ == '__main__':
    unittest.main()
