# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.appeals_case_reference import AppealsCaseReference

class TestAppealsCaseReference(unittest.TestCase):
    """AppealsCaseReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppealsCaseReference:
        """Test AppealsCaseReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppealsCaseReference`
        """
        model = AppealsCaseReference()
        if include_optional:
            return AppealsCaseReference(
                url = '',
                appeals_case_id = 56
            )
        else:
            return AppealsCaseReference(
                url = '',
                appeals_case_id = 56,
        )
        """

    def testAppealsCaseReference(self):
        """Test AppealsCaseReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
