# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.patent_case_information import PatentCaseInformation

class TestPatentCaseInformation(unittest.TestCase):
    """PatentCaseInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PatentCaseInformation:
        """Test PatentCaseInformation
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PatentCaseInformation`
        """
        model = PatentCaseInformation()
        if include_optional:
            return PatentCaseInformation(
                number_of_cases = 56,
                findings = [
                    openapi_client.models.patent_findings.PatentFindings(
                        case_id = [
                            56
                            ], 
                        type = [
                            ''
                            ], 
                        winner = '', )
                    ]
            )
        else:
            return PatentCaseInformation(
                number_of_cases = 56,
                findings = [
                    openapi_client.models.patent_findings.PatentFindings(
                        case_id = [
                            56
                            ], 
                        type = [
                            ''
                            ], 
                        winner = '', )
                    ],
        )
        """

    def testPatentCaseInformation(self):
        """Test PatentCaseInformation"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
