# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.party_filter import PartyFilter

class TestPartyFilter(unittest.TestCase):
    """PartyFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PartyFilter:
        """Test PartyFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PartyFilter`
        """
        model = PartyFilter()
        if include_optional:
            return PartyFilter(
                include = [
                    56
                    ],
                exclude = [
                    56
                    ],
                include_plaintiff = [
                    56
                    ],
                exclude_plaintiff = [
                    56
                    ],
                include_defendant = [
                    56
                    ],
                exclude_defendant = [
                    56
                    ],
                include_third_party = [
                    56
                    ],
                exclude_third_party = [
                    56
                    ]
            )
        else:
            return PartyFilter(
        )
        """

    def testPartyFilter(self):
        """Test PartyFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
