# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.rulings import Rulings

class TestRulings(unittest.TestCase):
    """Rulings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Rulings:
        """Test Rulings
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Rulings`
        """
        model = Rulings()
        if include_optional:
            return Rulings(
                judgment_event = '',
                awarded_to_party_ids = [
                    56
                    ],
                awarded_against_party_ids = [
                    56
                    ],
                awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date()
            )
        else:
            return Rulings(
                judgment_event = '',
                awarded_to_party_ids = [
                    56
                    ],
                awarded_against_party_ids = [
                    56
                    ],
                awarded = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
        )
        """

    def testRulings(self):
        """Test Rulings"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
