# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.response_get_law_firm_law_firms_law_firm_id_get import ResponseGetLawFirmLawFirmsLawFirmIdGet

class TestResponseGetLawFirmLawFirmsLawFirmIdGet(unittest.TestCase):
    """ResponseGetLawFirmLawFirmsLawFirmIdGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ResponseGetLawFirmLawFirmsLawFirmIdGet:
        """Test ResponseGetLawFirmLawFirmsLawFirmIdGet
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ResponseGetLawFirmLawFirmsLawFirmIdGet`
        """
        model = ResponseGetLawFirmLawFirmsLawFirmIdGet()
        if include_optional:
            return ResponseGetLawFirmLawFirmsLawFirmIdGet(
                name = '',
                law_firm_id = 56,
                input_id = 56,
                url = ''
            )
        else:
            return ResponseGetLawFirmLawFirmsLawFirmIdGet(
                name = '',
                law_firm_id = 56,
                input_id = 56,
                url = '',
        )
        """

    def testResponseGetLawFirmLawFirmsLawFirmIdGet(self):
        """Test ResponseGetLawFirmLawFirmsLawFirmIdGet"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
