# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.supreme_court_or_rehearing_decision import SupremeCourtOrRehearingDecision

class TestSupremeCourtOrRehearingDecision(unittest.TestCase):
    """SupremeCourtOrRehearingDecision unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SupremeCourtOrRehearingDecision:
        """Test SupremeCourtOrRehearingDecision
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SupremeCourtOrRehearingDecision`
        """
        model = SupremeCourtOrRehearingDecision()
        if include_optional:
            return SupremeCourtOrRehearingDecision(
                docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decision = '',
                original_resolution_docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                original_resolution = ''
            )
        else:
            return SupremeCourtOrRehearingDecision(
                docket_entry_filed = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                decision = '',
        )
        """

    def testSupremeCourtOrRehearingDecision(self):
        """Test SupremeCourtOrRehearingDecision"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
