# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.judgment_event_filter import JudgmentEventFilter

class TestJudgmentEventFilter(unittest.TestCase):
    """JudgmentEventFilter unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> JudgmentEventFilter:
        """Test JudgmentEventFilter
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `JudgmentEventFilter`
        """
        model = JudgmentEventFilter()
        if include_optional:
            return JudgmentEventFilter(
                include = [
                    ''
                    ],
                exclude = [
                    ''
                    ]
            )
        else:
            return JudgmentEventFilter(
        )
        """

    def testJudgmentEventFilter(self):
        """Test JudgmentEventFilter"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
