# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.district_case_number_reference import DistrictCaseNumberReference

class TestDistrictCaseNumberReference(unittest.TestCase):
    """DistrictCaseNumberReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DistrictCaseNumberReference:
        """Test DistrictCaseNumberReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DistrictCaseNumberReference`
        """
        model = DistrictCaseNumberReference()
        if include_optional:
            return DistrictCaseNumberReference(
                url = '',
                district_case_id = 56,
                case_number = '',
                court = '',
                title = ''
            )
        else:
            return DistrictCaseNumberReference(
                url = '',
                district_case_id = 56,
                case_number = '',
                court = '',
                title = '',
        )
        """

    def testDistrictCaseNumberReference(self):
        """Test DistrictCaseNumberReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
