# coding: utf-8

"""
    Lex Machina API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 20241105
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.patents_api import PatentsApi


class TestPatentsApi(unittest.TestCase):
    """PatentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PatentsApi()

    def tearDown(self) -> None:
        pass

    def test_get_patent_patents_patent_number_get(self) -> None:
        """Test case for get_patent_patents_patent_number_get

        Get Patent
        """
        pass

    def test_get_patents_patents_get(self) -> None:
        """Test case for get_patents_patents_get

        Get Patents
        """
        pass


if __name__ == '__main__':
    unittest.main()
