basePath: "https://api.lexmachina.com"
disallowAdditionalPropertiesIfNotPresent: False
generateSourceCodeOnly: True
packageName: lexmachina
packageVersion: "1.2.7"
packageUrl: "https://pypi.org/project/lexmachina-client/"
projectName: python-lexmachina-api-client
