basePath: "https://api.lexmachina.com"
disallowAdditionalPropertiesIfNotPresent: False
generateSourceCodeOnly: True
packageName: lexmachina
packageVersion: "2.0.0.20250318"
packageUrl: "https://pypi.org/project/lexmachina-client/"
projectName: python-lexmachina-api-client
